<?php
// Dong Quang ==========================
@define ('_aboutus','About Us');
@define ('_products','Products');
@define ('_dealer','Dealer');
@define ('_customer','Customer');
@define ('_news','News');
@define ('_contact','Contact');
@define ('_tinhthanhpho','Province/City');
@define ('_contactform','Contact Form');
@define ('_clear','Clear');
@define ('_xemchitiet','View detail');
@define ('_loadmore','Load more');
@define ('_consultant','Consultant');
@define ('_recruitment','Recruitment');
@define ('_gallery','Gallery');
@define ('_luottruycap','Visited');
@define ('_danhmucsanpham','Catalogue products');
@define ('_giaban','Price');
@define ('_gioithieutongquan','Product detail');
@define ('_sanphamlienquan','Related products');
@define ('_contactus','Contact Us');
@define ('_product','Product');
@define ('_readmore','Read more');
@define ('_thongsokythuat','Specifications');
@define ('_tintuclienquan','Related news');
@define ('_contact_message','Please fill your information in this form! We will contact you soon.');
@define ('_noidungwebsite','Website content');
@define ('_khongcovideochosanphamnay','There is no video for this product now.');
@define ('_services','Service');
@define ('_catalogue','Catalogue');
@define ('_video','Video');
@define ('_danhmuc','Categories');
@define ('_taibieumau','Download forms');
@define ('_guiyeucaumuahang','Submit order');
@define ('','');
@define ('','');
@define ('','');
@define ('','');

// Header ===============================
@define ('_home','Home');
@define ('_gioithieu','About Us');
@define ('_sanpham','Product');
@define ('_tuyendung','Recruitment');
@define ('_lienhe','Contact Us');
@define ('_yeucaubaogia','Quotes request');
@define ('_tuvankienthuc','Consulting - Knowledge');
@define ('_doitacchienluoc','Strategic partners');
@define ('_hethongphanphoi','Distribution System');
@define ('_khongcothuvienanhchosanphamnay','There is no gallery for this product!');
@define ('_khongcovideochosanphamnay','There is no video for this product!');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('_timkiem','Keywords');
@define ('_ketquatimkiem','Search results');


// Content ===============================
@define ('_dienthoai','Phone');
@define ('_email','Email');
@define ('_diachi','Address');
@define ('_tieude','Title');
@define ('_noidung','Content');
@define ('_hoten','Full name');
@define ('_thongtinlienhe','Contact information');
@define ('_guilienhe','Send message');
@define ('_formlienhe','Contact form');
@define ('_formguiyeucaubaogia','Quotes request form');
@define ('_guiyeucau','Send request');
@define ('_diadiemgiaohang','Place of delivery');
@define ('_guilienhe','Send contact');
@define ('_khoahoc','Course');
@define ('_noidungdaotao','Training content');
@define ('_giangvien','Trainer');
@define ('_cackhoahoc','Courses');
@define ('_dangkyhoc','Register');
@define ('_hotenhocvien',"Student's name");
@define ('_khoadaotao','Courses');
@define ('_sanphamcungdanhmuc','Same category products');
@define ('_dangkytaikhoanmoi','Register new account');
@define ('_taikhoan','Account');
@define ('_videoclips','Video clips');
@define ('_cuahangmypham','Cosmetics store');
@define ('_chonkhoadaotao','Choose a course');
@define ('_videonoibat','Video hot');
@define ('_videolienquan','Related videos');
@define ('_tendichvu','Service');
@define ('_cacdichvu','Services');
@define ('_bookdichvu','Booking');
@define ('_chiasequa','Share with');
@define ('_buoctieptheo','Next step');
@define ('_dichvuerror','Please choose a service!');
@define ('_optionerror','Please choole an option');
@define ('_soluongerror','Please enter real quantity!');
@define ('_xem','View');
@define ('','');
@define ('','');
@define ('','');

@define ('_tenerror','Please type your name (at least 3 chars)!');
@define ('_dienthoaierror','Please type your number (at least 6 chars)!');
@define ('_emailerror','Your email is not correct format!');
@define ('_tieuderror','Please type title (at least 3 chars)!');
@define ('_diachierror','Please type address!');
@define ('_noidungerror','Please type content!');
@define ('_passworderror','Please type password (at least 6 chars)!');
@define ('_confirmationerror','Passwords are not the same!');
@define ('_tinhtperror','Please choose City!');
@define ('_quanerror','Please choose District!');
@define ('_emaildatontai','This email existing, please type another email!');
@define ('_dangnhapthatbai','Login fail, wrong <b>email</b> or <b>password</b>!');
@define ('_matkhaucukhongdung','Old password is not valid!');
@define ('_passwordnewerror','Please type new password (at least 6 chars)!');
@define ('_doimatkhauthanhcong','Your password has been changed!');
@define ('_capnhatthongtinthanhcong','Your information has been updated!');


// Tài khoản ===============================
@define ('_dangnhap','Sign in');
@define ('_dangky','Sign up');
@define ('_dangkyngay','Sign up now');
@define ('_quenmatkhau','Lost password');
@define ('_haydangnhap','If you have an account, please login!');
@define ('_chuacotaikhoan','Not have an account');
@define ('_haydangkyngay','Sign up now by clicking the button below.');
@define ('_matkhau','Password');
@define ('_xacnhanmatkhau','Confirm password');
@define ('_thongtincanhan','Personal information');
@define ('_thongtindangnhap','Sign in information');
@define ('_truongbatbuoc','Required');
@define ('_dangkytaikhoan','Sign up');
@define ('_thanhvien','Member');
@define ('_laylaimatkhau','Reset your password');
@define ('_nhapmaillaymatkhau','Please type your email below here. You will be sent a link to reset password.');
@define ('_trolaitrangdangnhap','Back to sign in page');
@define ('_gui','Send');
@define ('_thoat','Sign out');
@define ('_capnhatthongtin','Update information');
@define ('_emailcuaban','Your email');
@define ('_capnhatthongtintaikhoan','Up date personal information');
@define ('_doimatkhau','Change password');
@define ('_matkhaucu','Old password');
@define ('_matkhaumoi','New password');
@define ('_xacnhanmatkhaumoi','Confirm password');
@define ('','');
@define ('','');
@define ('','');
@define ('','');

// Gio hang =============================
@define ('_giohang','Cart');
@define ('_xoa','Delete');
@define ('_tongtien','Total');
@define ('_thanhtien','Amount');
@define ('_soluong','Quantity');
@define ('_giohangtrong','Cart empty');
@define ('_thanhtoan','Order');
@define ('_tieptucmuahang','Back to product page');
@define ('_capnhatgiohang','Update cart');
@define ('_loikeugoidangky','Sign up with us for faster order and follow you orders status v.v... You can order without register an account');
@define ('_muahangtructiephoacdangky','Order straight away or sign up');
@define ('_ghichu','Notes');
@define ('_guidonhang','Order');
@define ('_thanhtoandonhang','Order');
@define ('_tomtatdonhang','Orders summary');
@define ('_thongtinnguoinhanhang','Delivery information');
@define ('_dathangthanhcong',"<p>Your orders has been sent!</p><p>We will contact to you as soon as we can.</p><p><b><i>Thank you!</i></b></p>");
@define ('_tinhthanh','City / State');
@define ('_tatcatinhthanh','All');
@define ('_tendaily','reseller name');
@define ('_nhomsanphamnoibat','Highlight categories product');
@define ('_sanphamnoibat','Highlight products');
@define ('_captchaerror','Captcha error !');
@define ('_thongbao','Notification');
@define ('_guibinhluanthanhcong','Comment successfully sent!');


// Linh tinh ===============================
@define ('_giabanle','Price');
@define ('_muahang','Order Now');
@define ('_addcart','Add to cart');
@define ('_xemthem','View more');
@define ('_chuacobaiviet','There is no post in this folder.');
@define ('_chuacosanpham','There is no product in this folder.');
@define ('_noidungdangcuocapnhat','Content being updated.');
@define ('_xinquaylaisau','Please comback later, thank you!');
@define ('_baivietkhac','Other posts');
@define ('_xemtatca','View all');
@define ('_call','Call');
@define ('_thongtinchitiet','View detail');
@define ('_madonhang','Order code');
@define ('_ngay','Date');
@define ('_hinhanh','Image');
@define ('_ten','Name');
@define ('_gia','Price');
@define ('_sl','Qty');
@define ('_lichsumuahang','Order history');
@define ('_wishlist','Wish list');
@define ('_phaidangnhapdesudung','You need to log in to use this feature!');
@define ('_sanphamdaduocduavaowishlist','This product has been added to your wish list');
@define ('_mst','Business code');
@define ('_ngaydangky','Date');
@define ('_noicap','Released by');
@define ('_addcartsuccess','Add to cart success!');
@define ('','');


?>