<?php
// ABASEALs ==========================
@define ('_ngaydang','Đăng lúc');
@define ('_views','lượt xem');
@define ('_baivietlienquan','Bài viết liên quan');
@define ('_xacnhanrobot',"Vui lòng xác nhận: I'm not a robot!");
@define ('_quaylaitintuc','Quay lại Tin tức & Sự kiện');
@define ('_contactform','Để có phản hồi dịch vụ khách hàng nhanh chóng, vui lòng điền vào biểu mẫu bên dưới.');
@define ('_cactruongbatbuoc','Các trường bắt buộc được đánh dấu bằng *');
@define ('_thuonghieu','Thương hiệu');
@define ('_quymo','Quy mô');
@define ('_hosonangluc','Hồ sơ năng lực');
@define ('_giaychungnhan','Giấy chứng nhận');
@define ('_thuonghieu','Thương hiệu');
@define ('_sanpham','Sản phẩm');
@define ('_tatcasanpham','Tất cả sản phẩm');
@define ('_caidatvaxuly','Cài đặt và xử lý');
@define ('_kichthuoclapdat','Kích thước lắp đặt');
@define ('_thuoctinhvatlieu','Thuộc tính vật liệu');
@define ('_khanangniemphong','Khả năng niêm phong');
@define ('_chitietkythuat','Chi tiết kỹ thuật');
@define ('_back','Quay lại');
@define ('_addtocart','Thêm vào giỏ hàng');
@define ('_mausac','Màu sắc');
@define ('_vatlieucoban','Vật liệu cơ bản');
@define ('_docung','Độ cứng');
@define ('_motathuongmai','Mô tả thương mại');
@define ('_chon','Chọn');
@define ('_vuilongchonpart','Vui lòng chọn part!');
@define ('_yeucaubaogia','Yêu cầu báo giá');
@define ('_giohangcuaban','Giỏ hàng của bạn');
@define ('_xacnhangiohang','Xác nhận giỏ hàng');
@define ('_thongtingiaohang','Thông tin giao hàng');
@define ('_diachigiaohang','Địa chỉ giao hàng');
@define ('_thongtinkhac','Thông tin khác');
@define ('_trolaigiohang','Trở lại giỏ hàng');
@define ('_dathang','Đặt hàng');
@define ('_duongkinhtrongid','Đường kính trong ID');
@define ('_duongkinhngoaiod','Đường kính ngoài OD');
@define ('_chieucaophoth1','Chiều cao phốt H1');
@define ('_chieucaokhelaph2','Chiều cao khe lắp H2');
@define ('_loaisanpham','Loại sản phẩm');
@define ('_timsanpham','Tìm sản phẩm');
@define ('_tatcadanhmuc','Tất cả danh mục');
@define ('','');
@define ('','');
@define ('','');


// General ==========================
@define ('_kiemtradonhang','Kiểm tra đơn hàng');
@define ('_loigioithieu','Lời giới thiệu');
@define ('_sanphamchungtoi','Sản phẩm của chúng tôi');
@define ('_xemthemsanpham','Xem thêm sản phẩm');
@define ('_ankhoesongkhoe','Ăn khỏe sống khỏe');
@define ('_tintuckhuyenmai','Tin tức khuyến mãi');
@define ('_taisaolachungtoi','Tại sao là chúng tôi');
@define ('_timkiemdes','Tìm kiếm sản phẩm, thương hiệu hay nhãn hàng mong muốn …');
@define ('_xemtiep','Xem tiếp');
@define ('_banchay','Bán chạy');
@define ('_moi','Mới');
@define ('_sanphamshoponline','Sản phẩm shop online');
@define ('_themvaodanhsachyeuthich','Thêm vào ưa thích của tôi');
@define ('_vuilonggoitructiepdecogiatotnhat','Vui lòng gọi <a href="tel:'.$row_setting['hotline'].'">'.$row_setting['hotline'].'</a> để được tư vấn rõ hơn');
@define ('_tintuclienquan','Tin tức liên quan');
@define ('_dangkynhantin','Đăng ký nhận tin');
@define ('_dangkynhantin_des','Đăng ký nhận tin từ Naman Market<br/>và nhận voucher điện tử');
@define ('_congty','Công ty');
@define ('_giomocua','Giờ mở cửa');
@define ('_xemngay','Xem ngay');
@define ('_thoigiangiaohang','Thời gian giao hàng');
@define ('_gio','Giờ');
@define ('_phut','Phút');
@define ('_laythongtinnguoimuahang','Lấy thông tin người mua hàng');
@define ('_muangay','Mua ngay');
@define ('_thucphamchay','Thực phẩm chay');
@define ('_khuyenmai','Khuyến mãi');
@define ('_sanphamkhuyenmai','Sản phẩm khuyến mãi');
@define ('_sanphambanchay','Sản phẩm bán chạy');
@define ('_xuatxu','Xuất xứ');
@define ('_quycachdonggoi','Quy cách đóng gói');
@define ('_motachung','Mô tả chung');
@define ('_giatridinhduong','Giá trị dinh dưỡng');
@define ('_quydinh_chinhsach','Quy định & Chính sách');
@define ('_sanphambanchaynhat','Sản phẩm bán chạy nhất');
@define ('_nhapmagiamgia','Nhập mã giảm giá');
@define ('_sudungmagiamgia','Sử dụng mã giảm giá');
@define ('_magiamgiamota','Mã giảm giá sẽ áp dụng trên tổng đơn hàng và làm tròn theo quy định của NamAnMarket');
@define ('_magiamgiakhonghoplehoacdahetthoihansudung','Mã giảm giá không hợp lệ hoặc đã hết hạn sử dụng.<br/>Vui lòng nhập mã khác, hoặc liên hệ để được hướng dẫn.');
@define ('_magiamgiakhongtontai','Mã giảm giá không tồn tại.');
@define ('_noidungnaykhongtontai','Nội dung này không còn tồn tại.');
@define ('_apdung','Áp dụng');
@define ('_banphaidangnhapdesudungchucnangnay','Bạn phải đăng nhập để sử dụng tính năng này.');

@define ('_giaodichthanhcong','Giao dịch thành công');
@define ('_giaodichpending','Giao dịch Pendding');
@define ('_giaodichthatbai','Giao dịch thất bại');
@define ('_kiemtramaildebietthemchitiet','Vui lòng kiểm tra email để biết thêm thông tin chi tiết.');
@define ('_donhangduocduavetrangthaicho','Đơn hàng được đưa về trạng thái chờ xử lý');

@define ('_thaydoithongtin','Thay đổi thông tin');
@define ('_huongdanchuyenkhoannganhang','Hướng dẫn chuyển khoản ngân hàng');
@define ('_tongsotiencanchuyenkhoan','Tổng số tiền chuyển khoản');
@define ('_chinhxac','Chính xác');
@define ('_trongmoitruonghop','trong mọi trường hợp');
@define ('_khonglamtron_ect_','(Vui lòng không làm tròn, không cộng gộp nhiều đơn hàng, vì <b>đây là thông tin nhận dạng duy nhất</b> cho đơn hàng của bạn)');
@define ('_vuilongchiuphichuyenkhoan','Vui lòng chịu phí chuyển khoản để <b>NamAnMarket</b> nhận được chính xác số tiền trên.');
@define ('_noidungghichu','Nội dung (ghi chú)');
@define ('_dongydieukhoan','Bằng việc nhấp vào <b>[THANH TOÁN]</b>, bạn đã đồng ý với các <b>Điều khoản & Điều kiện</b> của chúng tôi!');
@define ('_danhgiadichvu','Đánh giá dịch vụ');
@define ('_tieptuc','Tiếp tục');
@define ('_trolai','Trở lại');
@define ('_noidungdanhgia','Nội dung đánh giá');
@define ('_nhapnoidungdanhgia','Anh chị vui lòng cho biết cảm nhận chung của anh chị khi nhắc về Nam An');
@define ('_nhanxet','nhận xét');
@define ('_sanphamduocdexuat','Sản phẩm được đề xuất');
@define ('_loadmore','Xem thêm');
@define ('_capnhat_danhgiadichvuthanhcong','<b>Đánh giá của bạn đã được ghi nhận.</b><br/>Cảm ơn bạn đã đóng góp ý kiến!');
@define ('_danhgiadichvuthanhcong','<b>Đánh giá của bạn đã được ghi nhận.</b><br/>Cảm ơn bạn đã đóng góp ý kiến!');
@define ('_gockhachhang','Cảm nhận của khách hàng');
@define ('_camnhan','Cảm nhận');
@define ('_dexuat','Đề xuất');
@define ('_cothebanquantam','Sản phẩm kết hợp');
@define ('_thongbaovoitoikhicohang','Vui lòng thông báo cho tôi khi có hàng!');
@define ('_dong','Đóng');
@define ('_dangkythonbbaothanhcong','Cảm ơn bạn đã quan tâm đến sản phẩm của chúng tôi!<br/>Chúng tôi sẽ thông báo cho bạn ngay khi có hàng');
@define ('_dangkythonbbaotrung','Gửi không thành công!');
@define ('_xem','Xem');
@define ('_copyrights','Bản quyền website thuộc về <a href="http://namanmarket.com/vi/gioi-thieu.html"><b>Công ty TNHH Đầu tư Quốc tế Nam An</b></a>. All Rights Reserved');
@define ('_sanphammoi','Sản phẩm mới');
@define ('_trangkhongtontai','RẤT TIẾC, TRANG BẠN TÌM KIẾM KHÔNG TỒN TẠI');
@define ('_hoactrovetrangchu','Hoặc trở về trang chủ');
@define ('_neucanhotrovuilonggoi','Nếu bạn cần hỗ trợ, vui lòng gọi');
@define ('_khongtimthayketquanao','Không tìm thấy kết quả nào!');
@define ('_haythulaivoitukhoakhac','Hãy thử lại với từ khóa khác.');
@define ('_products','sản phẩm');
@define ('_chonnganhhang','Chọn ngành hàng');
@define ('_sanphamgoiy','Sản phẩm gợi ý');
@define ('_khongduhang','<p><b>KHÔNG CÒN ĐỦ SỐ LƯỢNG HÀNG!</b></p>Xin lỗi bạn, Nam An Market không còn đủ số lượng hàng bạn đặt.<br/>Vui lòng điều chình lại số lượng.');
@define ('_khongcondusoluonghangtoida','Không đủ số lượng cho sản phẩm này. Tối đa: ');
@define ('','');
@define ('','');

// Hee Master ==========================
@define ('_langtitle','English');
@define ('_hotline','Hotline');
@define ('_cuahang','Cửa hàng');
@define ('_blogs','Blogs');
@define ('_hocvien','Học viên');
@define ('_chiase','Chia sẻ');
@define ('_dichvunoibat','Dịch vụ nổi bật');
@define ('_dangkynhanthongtin','Đăng ký nhận thông tin khóa học mới');
@define ('_lienheheemaster','Liên hệ Hee Master');
@define ('_newsletter','News letter');
@define ('_lienhengay','Liên hệ ngay');
@define ('_tintucnoibat','Tin tức nổi bật');
@define ('_tintucsukiennoibattaiheemaster','Tin tức - Sự kiện nổi bật tại HeeMaster');
@define ('_doinguchuyengia','Đội ngũ chuyên gia');
@define ('_doinguchuyengia_des','Đội ngũ chuyên gia hội tụ nhiều tiêu chí, trong đó quan trọng nhất là chuyên môn');
@define ('_veheemaster','Về HeeMaster');
@define ('_thuvien','Thư viện');
@define ('_thuvienanh','Thư viện ảnh');
@define ('_dangxuat','Thoát');
@define ('_tailieu','Tài liệu');
@define ('_dichvunoibattaiheemaster','Các dịch vụ nổi bật tại HeeMaster');
@define ('_khuyennghidichvu','Tác dụng có thể khác nhau tuỳ cơ địa của người dùng');
@define ('_khoahocnoibattrongtuan','Khóa học nổi bật trong tuần');
@define ('_dichvunoibattrongtuan','Dịch vụ nổi bật trong tuần');
@define ('_followusonfacebook','Follow us on facebook');
@define ('_tinmoinhat','Tin mới nhất');
@define ('_tinhot','Tin hot');
@define ('_tinvideo','Tin video');
@define ('_tamdiem','Tâm điểm');


// Le Hieu ==========================
@define ('_vechungtoi','Về chúng tôi');
@define ('_banggiadichvu','Bảng giá / Dịch vụ');
@define ('_mypham','Mỹ phẩm');
@define ('_thongtinlamdep','Thông tin làm đẹp');
@define ('_daotao','Đào tạo');
@define ('_bosuutap','Bộ sưu tập');
@define ('_lienhevoichungtoi','Liên hệ với chúng tôi');
@define ('_danhmuc','Danh mục');
@define ('_hovaten','Họ & Tên');
@define ('_ngaysinh','Ngày sinh');
@define ('_quequan','Quê quán');
@define ('_facebook','Facebook');
@define ('_mautocthuchienboi','Mẫu tóc thực hiện bởi');
@define ('_dichvu','Dịch vụ');
@define ('_banggia','Bảng giá');
@define ('_khoadocerror','Hãy chọn 1 khoá đào tạo!');
@define ('_giaban','Giá bán');
@define ('_phanhoitukhachhang','Phản hồi từ khách hàng');
@define ('_danghangkhongcandangky','Đặt hàng không cần đăng ký');

@define ('_capdothanhvien','Cấp độ thành viên');
@define ('_giamgia','Giảm giá');
@define ('_chotatcadonhang','cho tất cả đơn hàng và dịch vụ');
@define ('_loai','Loại');
@define ('_tinnoibat','Tin nổi bật');
@define ('_downloadbanggia','Download file bàng giá');
@define ('_cart','Giỏ hàng');
@define ('','');

// TTB ===============================
@define ('_hotrokhachhang','Hỗ trợ khách hàng');
@define ('_tintuc','Tin tức');
@define ('_ngonngu','Ngôn ngữ');
@define ('_hethongcuahang','Hệ thống cửa hàng');
@define ('_dangkynhanmail','Nhập email để nhận tin / mã khuyến mãi điện tử');
@define ('_subscribe','Đăng ký');
@define ('_chontinhthanh','Chọn tỉnh thành');
@define ('_masanpham','Mã sản phẩm');
@define ('_chitiet','Chi tiết');
@define ('_xemchitiet','Xem chi tiết');
@define ('_khachhang','Khách hàng');
@define ('_thanhtich','Thành tích');
@define ('_mota','Mô tả');
@define ('_danhgia','Đánh giá');
@define ('_banggiadichvutailehieu','Bảng giá dịch vụ tại Salon Lê Hiếu');
@define ('_chonloaidichvu','Chọn loại dịch vụ');
@define ('_chonoption','Chọn option');
@define ('_tongcong','Tổng cộng');
@define ('','');
@define ('','');

// linh tinh ------------------------------------
@define ('_dangkyemailthanhcong','Đã đăng ký email thành công!');
@define ('_emaildaduocdangkytruocday','Email của bạn đã được đăng ký trước đây');
@define ('_thanhtoanbangtienmat','Thanh toán bằng tiền mặt');
@define ('_chuyenkhoannganhang','Chuyển khoản ngân hàng / ATM');
@define ('_thanhtoanonline','thanh toán online với OnePAY');
@define ('_thanhtoanonlinebangthenoidia','Thanh toán online bằng thẻ ATM nội địa');
@define ('_thanhtoanonlinebangthequocte','Thanh toán online bằng thẻ thanh toán quốc tế (VISA/MASTER)');
@define ('_hinhthucthanhtoan','Hình thức thanh toán');
@define ('_thongbao','Thông báo');
@define ('_guibinhluan','Gửi bình luận');
@define ('_guibinhluanthanhcong','Gửi bình luận thành công');
@define ('_thongtinlienlac','Thông tin liên lạc');
@define ('_thongtinkhachhang','Thông tin khách hàng');
@define ('_dongydattour','Đồng ý đặt tour');
@define ('_dongydatve','Đồng ý đặt vé');
@define ('_agreeerror','Hãy xác nhận bạn đã dọc hướng dẫn và đồng ý điều lệ thỏa thuận');
@define ('_confirmbooktour','Đã đọc <b>hướng dẫn book Tour</b> và đồng ý <b>điều lệ thỏa thuận</b> của <b class="hl">Zagovn.com</b>');
@define ('_toithieu10kitu','Tối thiểu 10 kí tự');
@define ('_khongchualienket','Không chứa liên kết');
@define ('_guinhanxetchozagovn','Gửi nhận xét cho ZAGOVN');
@define ('_lienkettaikhoan','Liên kết tài khoản');
@define ('_traloi','Trả lời');
@define ('_dangxuat','Đăng xuất');
@define ('_dangnhapthatbai','Đăng nhập thất bại!');
@define ('_hoacnhapthongtincuaban','Hoặc nhập thông tin của bạn');
@define ('_dangnhapbang','Đăng nhập bằng');
@define ('_lichsudonhang','Lịch sử đơn hàng');
@define ('_madonhang','Mã ĐH');
@define ('_ngay','Ngày');
@define ('_songay','ngày');
@define ('_sodem','đêm');
@define ('_trangthai','Trạng thái');
@define ('_sl','SL');
@define ('_ten','Tên');
@define ('_hinhanh','Hình ảnh');
@define ('_binhluanerror','Nội dung bình luận phải tối thiểu 10 kí tự!');


// Header ===============================
@define ('_home','Trang chủ');
@define ('_sanpham','Sản phẩm');
@define ('_tuyendung','Tuyển dụng');
@define ('_lienhe','Liên hệ');
@define ('_gioithieu','Giới thiệu');
@define ('_tuvankienthuc','Tư vấn - Kiến thức');
@define ('_doitacchienluoc','Đối tác chiến lược');
@define ('_tuyendung','Tuyển dụng');
@define ('_hethongphanphoi','Hệ thống phân phối');
@define ('_hethongphanphoi','Hệ thống phân phối');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('','');
@define ('_timkiem','Tìm kiếm');
@define ('_ketquatimkiem','Kết quả tìm kiếm');

// Content ===============================
@define ('_dienthoai','Điện thoại');
@define ('_email','Email');
@define ('_diachi','Địa chỉ');
@define ('_tieude','Tiêu đề');
@define ('_noidung','Nội dung');
@define ('_hoten','Họ / Tên');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_formlienhe','Form gửi liên hệ');
@define ('_guilienhe','Gửi liên hệ');
@define ('_formguiyeucaubaogia','Form gửi yêu cầu báo giá');
@define ('_guiyeucau','Gửi yêu cầu');
@define ('_diadiemgiaohang','Địa điểm giao hàng');
@define ('_nhomsanphamnoibat','Nhóm sản phẩm nổi bật');
@define ('_sanphamnoibat','Sản phẩm nổi bật');
@define ('_khoahoc','Khóa học');
@define ('_noidungdaotao','Nội dung đào tạo');
@define ('_giangvien','Giảng viên');
@define ('_cackhoahoc','Các khóa học');
@define ('_dangkyhoc','Đăng ký học');
@define ('_hotenhocvien','Họ tên học viên');
@define ('_khoadaotao','Khóa đào tạo');
@define ('_sanphamcungdanhmuc','Sản phẩm tương tự được yêu thích');
@define ('_dangkytaikhoanmoi','Đăng ký tài khoản mới');
@define ('_taikhoan','Tài khoản');
@define ('_videoclips','Video clips');
@define ('_cuahangmypham','Cửa hàng mỹ phẩm');
@define ('_chonkhoadaotao','Chọn khóa đào tạo');
@define ('_videonoibat','Video nổi bật');
@define ('_videolienquan','Video liên quan');
@define ('_tendichvu','Tên dịch vụ');
@define ('_cacdichvu','Các dịch vụ');
@define ('_bookdichvu','Book dịch vụ');
@define ('_chiasequa','Chia sẽ qua');
@define ('_buoctieptheo','Tiếp tục');
@define ('_dichvuerror','Hãy chọn 1 dịch vụ!');
@define ('_optionerror','Hãy chọn 1 option');
@define ('_soluongerror','Hãy cập nhật số lượng thật!');
@define ('','');


@define ('_tenerror','Vui lòng nhâp tên (ít nhất 3 kí tự)!');
@define ('_dienthoaierror','Vui lòng nhập số điện thoại (ít nhất 6 kí tự)!');
@define ('_diachierror','Vui lòng nhập địa chỉ (ít nhất 10 kí tự)!');
@define ('_emailerror','Vui lòng nhâp email đúng định dạng!');
@define ('_tieuderror','Vui lòng nhâp tiêu đề (ít nhất 3 kí tự)!');
@define ('_noidungerror','Vui lòng nhâp nội dung!');
@define ('_passworderror','Vui lòng nhâp mật khẩu (ít nhất 6 kí tự)!');
@define ('_confirmationerror','Mật khẩu không trùng nhau!');
@define ('_emaildatontai','Email đã có người sử dụng, vui lòng nhập email khác!');
@define ('_dangnhapthatbai','Đăng nhập thất bại, <b>email</b> hoặc <b>mật khẩu</b> không đúng!');
@define ('_matkhaucukhongdung','Mật khẩu cũ không đúng!');
@define ('_passwordnewerror','Vui lòng nhâp mật khẩu mới (ít nhất 6 kí tự)!');
@define ('_doimatkhauthanhcong','Đổi mật khẩu thành công!');
@define ('_capnhatthongtinthanhcong','Cập nhật thông tin thành công!');




// Tài khoản ===============================
@define ('_dangnhap','Đăng nhập');
@define ('_dangky','Đăng ký');
@define ('_dangkybang','Đăng ký bằng');
@define ('_dangkyngay','Đăng ký ngay');
@define ('_quenmatkhau','Quên mật khẩu');
@define ('_haydangnhap','Nếu bạn đã có tài khoản. Hãy đăng nhập');
@define ('_chuacotaikhoan','Bạn chưa có tài khoản');
@define ('_haydangkyngay','Hãy đăng ký ngay bằng cách click vào nút bên dưới.');
@define ('_matkhau','Mật khẩu');
@define ('_xacnhanmatkhau','Xác nhận mật khẩu');
@define ('_thongtincanhan','Thông tin cá nhân');
@define ('_thongtindangnhap','Thông tin đăng nhập');
@define ('_truongbatbuoc','Trường bắt buộc');
@define ('_dangkytaikhoan','Đăng ký tài khoản');
@define ('_thanhvien','Thành viên');
@define ('_laylaimatkhau','Lấy lại mật khẩu');
@define ('_nhapmaillaymatkhau','Vui lòng nhập email của bạn dưới đây. Bạn sẽ nhận được một liên kế để đặt lại mật khẩu.');
@define ('_trolaitrangdangnhap','Trở lại trang đăng nhập');
@define ('_gui','Gửi');
@define ('_thoat','Thoát');
@define ('_capnhatthongtin','Cập nhật thông tin');
@define ('_emailcuaban','Email của bạn');
@define ('_capnhatthongtintaikhoan','Cập nhật thông tin tài khoản');
@define ('_doimatkhau','Đổi mật khẩu');
@define ('_matkhaucu','Mật khẩu cũ');
@define ('_matkhaumoi','Mật khẩu mới');
@define ('_xacnhanmatkhaumoi','Xác nhận mật khẩu mới');
@define ('','');
@define ('','');
@define ('','');
@define ('','');

// Gio hang =============================
@define ('_giohang','Giỏ hàng');
@define ('_xoa','Xoá');
@define ('_tongtien','Tổng tiền');
@define ('_thanhtien','Thành tiền');
@define ('_soluong','Số lượng');
@define ('_giohangtrong','Giỏ hàng trống');
@define ('_thanhtoan','Thanh toán');
@define ('_tieptucmuahang','Tiếp tục mua hàng');
@define ('_capnhatgiohang','Cập nhật giỏ hàng');
@define ('_loikeugoidangky','Đăng ký với chúng tôi để thanh toán nhanh hơn, để theo dõi tình trạng đặt hàng của bạn v.v... Bạn cũng có thể thanh toán mà không cần đăng ký tài khoản');
@define ('_muahangtructiephoacdangky','Mua hàng trực tiếp hoặc đăng ký mới tài khoản');
@define ('_ghichu','Ghi chú');
@define ('_guidonhang','Gửi đơn hàng');
@define ('_thanhtoandonhang','Thanh toán đơn hàng');
@define ('_tomtatdonhang','Tóm tắt đơn hàng');
@define ('_thongtinnguoimuahang','Thông tin người mua hàng');
@define ('_thongtinnguoinhanhang','Thông tin người nhận hàng');
@define ('_dathangthanhcong',"<p>Đơn hàng của bạn đã được gửi thành công!</p><p>Chúng tôi sẽ phản hồi sớm nhất có thể.</p><p><b><i>Xin cảm ơn!</i></b></p>");
@define ('_tinhthanh','Tỉnh / Thành phố');
@define ('_tatcatinhthanh','Tất cả tỉnh thành');
@define ('_tendaily','Tên đại lý');
@define ('','');
@define ('','');
@define ('','');


// Linh tinh ===============================
@define ('_giabanle','Giá bán lẻ');
@define ('_muahang','Mua ngay');
@define ('_addcart','Thêm vào giỏ');
@define ('_xemthem','Xem thêm');
@define ('_chuacobaiviet','Chưa có bài viết nào trong danh mục này.');
@define ('_chuacosanpham','Chưa có sản phẩm nào trong danh mục này.');
@define ('_noidungdangcuocapnhat','Nội dung đang được cập nhật.');
@define ('_xinquaylaisau','Xin vui lòng quay lại sau, Cảm ơn!');
@define ('_baivietkhac','Bài viết khác');
@define ('_baivietlienquan','Bài viết liên quan');
@define ('_xemtatca','Xem tất cả');
@define ('_call','Liên hệ');
@define ('_thongtinchitiet','Thông tin chi tiết');
@define ('_ngay','Ngày');
@define ('_hinhanh','Hình ảnh');
@define ('_ten','Tên');
@define ('_gia','Giá');
@define ('_sl','SL');
@define ('_lichsumuahang','Lịch sử mua hàng');
@define ('_wishlist','Sản phẩm ưa thích');
@define ('_phaidangnhapdesudung','Bản phải đăng nhập để sử dụng chức năng này!');
@define ('_sanphamdaduocduavaowishlist','Sản phẩm này đã được dưa vào danh sách ưa thích của bạn');
@define ('_mst','MST');
@define ('_ngaydangky','Ngày đăng ký');
@define ('_noicap','Nơi cấp');
@define ('_addcartsuccess','Sản phẩm đã được thêm vào giỏ hàng');

?>